version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

language: scala

addons:
  apt:
    packages:
      # To debug docs generation
      - tree

git:
  depth: false # Avoid sbt-dynver not seeing the tag

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11

scala:
  - 2.11.12
  - 2.12.15
  - 2.13.8
  - 3.0.2

script:
  - ./scripts/tests.sh
  - ./scripts/validate-docs.sh

stages:
  - name: test
  - name: release
    if: tag IS present

jobs:
  include:
  - stage: release
    script: sbt ci-release
